#! /bin/sh

# Init script for starting and stopping various kernel modules on system
# startup and shutdown

case "$1" in
    start)
        echo "Loading aesd-char driver..."
        aesdchar_load
        echo "Loading scull driver..."
        scull_load
        echo "Loading faulty driver..."
        module_load faulty
        echo "Loading hello module..."
        modprobe hello.ko
        ;;
    stop)
        echo "Unloading aesd-char driver..."
        aesdchar_unload
        echo "Unloading scull driver..."
        scull_unload
        echo "Unloading faulty driver..."
        module_unload faulty
        echo "Unloading hello module..."
        rmmod hello.ko
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac


exit 0